### ISSUE TITLE
Ruby 2.7/3.0 support

### ISSUE THREAD

**Issue by victorfgs** [palkan/abstract_notifier#12]
## Is your feature request related to a problem? Please describe.

When using this gem on projects with ruby 2.7 , there a few deprecation warnings that will break on ruby 3.0 (related to how ruby 3.0 handles keyword arguments).

## Describe the solution you'd like

Release a major version that drops support for ruby <= 2.6 (because this version already hit EOL) that fixes those warnings

## Describe alternatives you've considered

I've considered forking the project and fixing the deprecation warnings locally

## Additional context

I am currently working on fix those warnings. I hope to open a PR soon. Let me know if there's something else I can do here.

**Comment by palkan** [comment]
> I am currently working on fix those warnings. I hope to open a PR soon

Thank you!

**Comment by palkan** [comment]
Abstract Notifier has been merged into [Active Delivery](https://github.com/palkan/active_delivery) and supports modern Rubies now.
