### ISSUE TITLE
have_enqueued_notification fails when 2 notifications with same message are enqueued

### ISSUE THREAD

**Issue by kleber-gueriero** [palkan/abstract_notifier#3]
When testing a method that calls 2 different notification methods which sends exactly same message, the `expect` with `have_enqueued_notification` fails, saying that it wasn't enqueued not even once:

```
expected to enqueue notification: {:body=>"Here we go again"} exactly once, but haven't enqueued anything
```

I didn't test similar cases, like enqueue twice w/ same method, but at least the problem exists for this specific case.

**Comment by palkan** [comment]
Hey @kleber-gueriero!

Could you please provide a code example and a test example for this exception?'

P.S. Sorry for such a late response.

**Comment by SuzukiRyuichiro** [comment]
I can see a similar issue with `have_sent_notification` matcher as well.

I have two callbacks where each of them create notifications. 

Basically, when I have a test like

```rb
RSpec.describe Post, type: :model do
  describe 'notifications' do
      context 'when new post is published' do
        it { expect { create(:post) }.to have_sent_notification }
      end
    end
  end
end
```


```rb
class Post < ActiveRecord

  after_create :send_can_see_posts
  after_create :notify_new_post

  def send_can_see_posts
    FromAdminNotifier.send_can_see_posts(user: user).notify_now 
  end

  def notify_new_post
    NewPostNotifier.created(self).notify_now
  end
end
```

```
# frozen_string_literal: true

class NewPostNotifier < ApplicationNotifier
  def created(post)
    users = User.includes(:posts).where(posts: { published: true }).where.not(posts: { user: post.user })
    recipients = users.map { |user| { external_id: user.id.to_s } }

    notification(
      title: '新規年収投稿',
      body: "#{post.title}",
      category: :post,
      recipients: recipients
    )
  end
end

class FromAdminNotifier < ApplicationNotifier
  def send_can_see_posts(user:)
    recipient = { external_id: user.id.to_s }

    notification(
      title: 'Thanks for your post!',
      body: 'Thank you for your submission. Now you can see what others have posted on the platform!',
      category: :announcement,
      recipients: [recipient]
    )
  end
end
```
  
So creating a post sends two notifications. One to the user who have submitted to tell them that they can now see others post (we have some exclusive thread page like that), and another to rest of the users who have already submitted a post to tell them that there's a new post in the app. 

When one action sends two or more notifications, the matcher fails.
