### ISSUE TITLE
RSpec matchers doesn't work

### ISSUE THREAD

**Issue by brovikov** [palkan/abstract_notifier#5]
I have the same issue with testing like described [here](https://github.com/palkan/active_delivery/issues/12):
```
You must pass an argument rather than a block to use the provided matcher (have not delivered to MyDelivery), or the matcher must implement `supports_block_expectations?
```
**when spring is running.**

So adding `require "abstract_notifier/testing/rspec"` makes a trick! Let's add notice to the docs:
___
**NOTE:** test mode activated automatically if `RAILS_ENV` or `RACK_ENV` env variable is equal to "test". Otherwise add `require "abstract_notifier/testing/rspec"` to your `spec_helper.rb` / `rails_helper.rb manually`. This is also required if you're using Spring in test environment (e.g. with help of spring-commands-rspec).
___
    
Let me know if I could send PR or you will do it on yours end.

Thanks, for the great gem and all your open source works!

**Comment by palkan** [comment]
> Let me know if I could send PR or you will do it on yours end.

Sure. PR would be awesome!

Let's also change the RSpec check here to `defined?(RSpec::Core)`: https://github.com/palkan/abstract_notifier/blob/9f17ac96a6cacc35f2628563918f0f92529cdede/lib/abstract_notifier/testing.rb#L48
