### ISSUE TITLE
Option to disable default `notifier` line with ActiveDelivery?

### ISSUE THREAD

**Issue by thornomad** [palkan/abstract_notifier#8]
Would you be open to having an option (somewhere, not sure where) that would disable creating the default `notifier` _line_ for `ActiveDelivery`?  Looking at [these lines here](https://github.com/palkan/abstract_notifier/blob/2b154f993b770e554af31f88fab6d0fcfab8080f/lib/active_delivery/lines/notifier.rb#L40-L44):

```ruby
    # Only automatically register line when we can resolve the class
    # easily.
    if "".respond_to?(:safe_constantize)
      ActiveDelivery::Base.register_line :notifier, Notifier, resolver: Notifier::DEFAULT_RESOLVER
    end
```

I'm using name other than `notifier` and it would be nice to be able to disable the default so I don't have an extra line registering that I don't need.  Happy to do a pull request if you have insight on how you wan options handled.  Thanks for releasing these gems!

**Comment by palkan** [comment]
> Happy to do a pull request if you have insight on how you wan options handled.

What about adding `ActiveDelivery::Base.unregister_line`? Will it help in your case?

**Comment by thornomad** [comment]
I think that would work fine.  Would you like me to submit a PR or did you want to tackle it yourself?

**Comment by palkan** [comment]
> Would you like me to submit a PR or did you want to tackle it yourself?

That would be great if you submit a PR 🙂

**Comment by thornomad** [comment]
PR submitted on the active delivery repo.  Thanks.
